In [95]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [96]:
df = df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis= 1)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [97]:
target = df['Survived']
inputs  = df.drop(['Survived'],axis=1)

In [98]:
dummies = pd.get_dummies(inputs.Sex).astype(int)
dummies.head()

   female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [99]:
inputs = pd.concat([inputs,dummies],axis=1)
inputs.drop(['Sex'],axis=1,inplace=True)
inputs.head()

   Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [100]:
inputs['Age'] = inputs['Age'].fillna(inputs['Age'].mean())

In [101]:
inputs.isnull().sum()

Pclass    0
Age       0
Fare      0
female    0
male      0
dtype: int64

In [102]:
inputs.shape

(891, 5)

In [103]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(inputs,target,test_size=0.2)

In [104]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(712, 5)
(179, 5)
(712,)
(179,)

In [105]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [106]:
model.fit(X_train,y_train)

GaussianNB()

In [107]:
model.score(X_test,y_test)

0.7597765363128491

In [108]:
y_pred = model.predict(X_test)

In [109]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7597765363128491

In [110]:
from sklearn.naive_bayes import MultinomialNB

model1 = MultinomialNB()

model1.fit(X_train, y_train)

y_pred2 = model.predict(X_test)

In [111]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred2)

0.7597765363128491